apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: cdn-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: cdn.minikube.int
    http:
      paths:
      - path: /
        backend:
          serviceName: cdn-service
          servicePort: 80

