apiVersion: v1
kind: PersistentVolume
metadata:
  name: cdn-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/cdn-volume"

